"""Create Country table

Revision ID: 0203312d5a32
Revises: 
Create Date: 2023-01-08 19:33:00.889445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0203312d5a32"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("capital", sa.String(), nullable=False),
        sa.Column(
            "area", sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=True
        ),
        sa.Column(
            "population",
            sa.Numeric(precision=18, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column(
            "gdp_per_capita",
            sa.Numeric(precision=18, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("internet_country_code", sa.String(), nullable=True),
        sa.Column("flag_file_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_country_id"), "country", ["id"], unique=False)
    op.create_index(op.f("ix_country_name"), "country", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_country_name"), table_name="country")
    op.drop_index(op.f("ix_country_id"), table_name="country")
    op.drop_table("country")
    # ### end Alembic commands ###
